In [ ]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.datasets import load_boston

In [ ]:
boston = load_boston()

In [ ]:
boston

In [ ]:
boston.data

In [ ]:
boston.target

In [ ]:
boston.keys()

In [ ]:
boston.feature_names

In [ ]:
boston.DESCR

In [ ]:
df_bos = pd.DataFrame(boston.data, columns=boston.feature_names)

In [ ]:
df_bos

In [ ]:
df_bos.shape


In [ ]:
df_bos.columns

In [ ]:
df_bos['Target'] = boston.target

In [ ]:
df_bos

In [ ]:
df_bos.shape

In [ ]:
df_bos.isnull().sum()

In [ ]:
df_bos.dtypes

In [ ]:
sns.heatmap(df_bos.isnull())

In [ ]:
df_bos.describe()

In [ ]:
df_bos['CRIM'].plot.box()

In [ ]:
df_bos['INDUS'].plot.box()

In [ ]:
df_bos['ZN'].plot.box()

In [ ]:
df_bos.plot(kind='box', subplots = True, layout=(2, 7))

In [ ]:
from scipy.stats import zscore
z = np.abs(zscore(df_bos))
z

In [ ]:
threshold = 3
print(np.where(z>3))

In [ ]:
z[55][1]

In [ ]:
df_bos['CRIM'].plot.hist()

In [ ]:
df_bos['ZN'].plot.hist()

In [ ]:
df_bos['CRIM'] = np.log(df_bos['CRIM'])
#0 --> log transform
#.5 --> sqaure root transform

In [ ]:
from scipy.stats import boxcox
#df_bos['CRIM'] = boxcox(df_bos['CRIM'],0 or .5)

In [ ]:
df_bos['CRIM'].plot.hist()

In [ ]:
plt.scatter(df_bos['CRIM'], df_bos['Target'])
plt.title('Data')
plt.xlabel('CRIM')
plt.ylabel('Target')

In [ ]:
sns.pairplot(df_bos)

In [ ]:
corr_hmap = df_bos.corr()
plt.figure(figsize=(8,7))
sns.heatmap(corr_hmap, annot=True)
plt.show()

In [ ]:
plt.scatter(df_bos['Target'], df_bos['LSTAT'])

In [ ]:
df_bos.columns

In [ ]:
df_bos.drop('LSTAT', axis = 1, inplace=True)

In [ ]:
df_bos.columns

In [ ]:
new = df_bos[(z<3).all(axis=1)]# removing outliers

In [ ]:
new

In [ ]:
new.shape

In [ ]:
new.head()

In [ ]:
x = new.iloc[:,0:-1]

In [ ]:
x

In [ ]:
y = new.iloc[:,-1]

In [ ]:
y

In [ ]:
x.shape

In [ ]:
y.shape

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=33, random_state=42)

In [ ]:
x_train.shape

In [ ]:
y_train.shape

In [ ]:
lm = LinearRegression()

In [ ]:
lm.fit(x_train, y_train)

In [ ]:
lm.coef_

In [ ]:
lm.intercept_

In [ ]:
new.columns

In [ ]:
lm.score(x_train,y_train)

In [ ]:
pred = lm.predict(x_test)
print("the predicted value is", pred)
print("the previous value is", y_test)

In [ ]:
print("error:")

print("mean absolute error", mean_absolute_error(y_test, pred))
print("mean square error is", mean_squared_error(y_test, pred))

print("root mean squared error", np.sqrt(mean_squared_error(y_test, pred)))


In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,pred))

In [ ]:
lm.coef_

Lasso and Ridge regression 

Mainly used to reduce overfitting

In [ ]:
from sklearn.linear_model import Lasso, Ridge 

In [ ]:
ls = Lasso(alpha = 0.0001)
ls.fit(x_train, y_train)
ls.score(x_train, y_train)

In [ ]:
ls.coef_

In [ ]:
lf = Ridge(alpha = 0.0001)
lf.fit(x_train, y_train)
lf.score(x_train, y_train)

In [ ]:
lf.coef_

In [ ]:
from sklearn.linear_model import ElasticNet
enr = ElasticNet(alpha = 0.0001)
enr.fit(x_train, y_train)
pre = enr.predict(x_test)
print(enr.score(x_train, y_train))

In [ ]:
enr.coef_

In [ ]:
from sklearn.svm import SVR
from sklearn.metrics import r2_score

kernellist = ["linear", "poly", "rbf"]
for i in kernellist:
    snr = SVR(kernel = i)
    snr.fit(x_train,y_train)
    print(snr.score(x_train,y_train))
    predi = snr.predict(x_test)
    print("presicted value : ", predi)
    print("error:")
    print("mean absolute error", mean_absolute_error(y_test, predi))
    print("mean square error is", mean_squared_error(y_test, predi))
    print("root mean squared error", np.sqrt(mean_squared_error(y_test, predi)))
    print(r2_score(y_test,predi))
    
    


linear mode has high score so we will pick it



In [ ]:
from sklearn.tree import DecisionTreeRegressor

dc = DecisionTreeRegressor()
dc.fit(x_train, y_train)
print(dc.score(x_train,y_train))
predictor = dc.predict(x_test)
predictor
print("error:")
print("mean absolute error", mean_absolute_error(y_test, predictor))
print("mean square error is", mean_squared_error(y_test, predictor))
print("root mean squared error", np.sqrt(mean_squared_error(y_test, predictor)))
print(r2_score(y_test,predictor))


    



In [ ]:
from sklearn.neighbors import KNeighborsRegressor
kn = KNeighborsRegressor(n_neighbors= 1)
kn.fit(x_train,y_train)
print(kn.score(x_train,y_train))
predictorkn = kn.predict(x_test)
predictorkn
print("error:")
print("mean absolute error", mean_absolute_error(y_test, predictorkn))
print("mean square error is", mean_squared_error(y_test, predictorkn))
print("root mean squared error", np.sqrt(mean_squared_error(y_test, predictorkn)))
print(r2_score(y_test,predictorkn))
    

In [ ]:
from sklearn.ensemble import RandomForestRegressor
r = RandomForestRegressor()
r.fit(x_train,y_train)
print(r.score(x_train,y_train))
predictorR = r.predict(x_test)
predictorR
print("error:")
print("mean absolute error", mean_absolute_error(y_test, predictorR))
print("mean square error is", mean_squared_error(y_test, predictorR))
print("root mean squared error", np.sqrt(mean_squared_error(y_test, predictorR)))
print(r2_score(y_test,predictorR))
print("\n")

In [ ]:
models = [LinearRegression(), DecisionTreeRegressor(), KNeighborsRegressor(), RandomForestRegressor()]

for m in models:
    m.fit(x_train,y_train)
    print(m.score(x_train,y_train))
    predict_m = m.predict(x_test)
    print(predict_m)
    print("error:")
    print("mean absolute error", mean_absolute_error(y_test, predict_m))
    print("mean square error is", mean_squared_error(y_test, predict_m))
    print("root mean squared error", np.sqrt(mean_squared_error(y_test, predict_m)))
    print(r2_score(y_test,predict_m))
    print("\n")

In [ ]:
import pickle

with open("model_pickle", 'wb') as f:
    pickle.dump(dc, f)

In [ ]:
with open("model_pickle", 'rb') as f:
    obj = pickle.load(f)

In [185]:
import numpy as np
t = np.array([[0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9]])

In [186]:
t.shape

(1, 12)

In [187]:
t.reshape(1,-1)

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02]])

In [188]:
t.shape

(1, 12)

In [190]:
obj.predict(t)

array([24.])

In [192]:
from sklearn.externals import joblib
import warnings
warnings.filterwarnings('ignore')

joblib.dump(r, 'model_joblib')

['model_joblib']

In [193]:
j = joblib.load('model_joblib')

In [199]:
l = np.array([[0.62976,0,8.14,0,0.538,5.949,61.8,4.7075,4,307,21,396.9]])
l.shape

(1, 12)

In [200]:
l.reshape(1, -1)

array([[  0.62976,   0.     ,   8.14   ,   0.     ,   0.538  ,   5.949  ,
         61.8    ,   4.7075 ,   4.     , 307.     ,  21.     , 396.9    ]])

In [201]:
l.shape

(1, 12)

In [202]:
j.predict(l)

array([20.322])