In [1]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4])

In [7]:
a

array([1, 2, 3, 4])

In [8]:
a.dtype

dtype('int64')

In [12]:
type(a)

numpy.ndarray

In [13]:
a.shape

(4,)

In [15]:
a.reshape(1, -1)

array([[1, 2, 3, 4]])

In [17]:
a.shape

(4,)

In [19]:
a.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])

In [20]:
a.shape

(4,)

In [21]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12,13, 14, 15], [16, 17, 18, 19, 20]])

In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
a[2,3] = 15

In [25]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 15, 15],
       [16, 17, 18, 19, 20]])

In [26]:
a[:3,0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 15, 15]])

In [27]:
I = np.eye(10)

In [28]:
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.full((4,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [42]:
x = np.random.random((2,4))

In [46]:
x.var()

0.06835688724779769

In [41]:
np.random.randint((2,4))

array([1, 0])

$$ MATRIX METHODS $$