In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(4,)

In [7]:
a.reshape(1, -1)

array([[1, 2, 3, 4]])

In [8]:
a.shape

(4,)

In [9]:
a.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])

In [10]:
a.shape

(4,)

In [11]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12,13, 14, 15], [16, 17, 18, 19, 20]])

In [12]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
a[2,3] = 15

In [15]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 15, 15],
       [16, 17, 18, 19, 20]])

In [16]:
a[:3,0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 15, 15]])

In [17]:
I = np.eye(10)

In [18]:
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.full((4,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [22]:
x = np.random.random((2,4))

In [23]:
x.var()

0.05209590473700665

In [24]:
np.random.randint((2,4))

array([0, 2])

$$ MATRIX METHODS $$

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [28]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
x[:],x[1:4],x[1:],x[2,3]

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 14)

In [37]:
np.random.randn(2,2)

array([[-0.71927564,  0.30637409],
       [-0.87419482, -0.91855932]])

In [40]:
np.random.randint((2,2))

array([0, 0])

In [42]:
x = np.array(np.random.randn(3,3))
y = np.array(np.random.randn(3,3))

In [43]:
x+y

array([[-1.47567458,  0.87512905,  0.73637189],
       [ 1.75777971, -1.68575525,  0.19132426],
       [ 1.36530904, -0.46002274,  1.68071269]])

In [44]:
x-y

array([[-0.18297036, -1.72172619, -0.1141858 ],
       [-0.76911666,  1.28803294,  1.79703795],
       [ 0.72389924,  1.22200018,  0.38635449]])

In [45]:
x*y

array([[ 0.53603433, -0.54962256,  0.13230129],
       [ 0.62456227,  0.29568547, -0.79818511],
       [ 0.33500966, -0.32041588,  0.66888134]])

In [48]:
z = np.multiply(x, y)

In [49]:
z

array([[ 0.53603433, -0.54962256,  0.13230129],
       [ 0.62456227,  0.29568547, -0.79818511],
       [ 0.33500966, -0.32041588,  0.66888134]])

In [50]:
np.dot(x,y)

array([[ 0.10098758, -0.70904787,  0.18848777],
       [-0.25192423,  0.10142148,  1.01329901],
       [ 0.13763671, -0.0793606 ,  0.80724998]])

In [52]:
x/y

array([[ 1.28308156, -0.3260086 ,  0.73150369],
       [ 0.39125587,  0.13374265, -1.23830433],
       [ 3.25721293, -0.45301252,  1.59698233]])

In [58]:
np.matmul(x,y)

In [56]:
x,x.T

(array([[-0.82932247, -0.42329857,  0.31109304],
        [ 0.49433152, -0.19886115,  0.99418111],
        [ 1.04460414,  0.38098872,  1.03353359]]),
 array([[-0.82932247,  0.49433152,  1.04460414],
        [-0.42329857, -0.19886115,  0.38098872],
        [ 0.31109304,  0.99418111,  1.03353359]]))

In [57]:
np.inner(x,y)

array([[ 0.11871306, -0.668169  ,  0.29136409],
       [-0.15491484,  0.12206264,  0.96919228],
       [ 0.25904416, -0.07646619,  0.68347512]])