In [64]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [65]:
import numpy as np


In [66]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [67]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])

print(a)

a = a.reshape(2,3)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [68]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])
b = np.array([[1,2,3], [4,5,6]])

np.dot(a,b)



array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [69]:
import numpy as np
a = np.array([1, 2, 3, 4], dtype = complex)
print(a)
a.itemsize
type(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


numpy.ndarray

In [70]:
a = np.array

In [71]:
pip instal pandas

ERROR: unknown command "instal" - maybe you meant "install"
Note: you may need to restart the kernel to use updated packages.


In [72]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [73]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [74]:
import numpy as np
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
cp = np.ones((2,3))

In [76]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
np.linspace(2, 500, 20)

array([  2.        ,  28.21052632,  54.42105263,  80.63157895,
       106.84210526, 133.05263158, 159.26315789, 185.47368421,
       211.68421053, 237.89473684, 264.10526316, 290.31578947,
       316.52631579, 342.73684211, 368.94736842, 395.15789474,
       421.36842105, 447.57894737, 473.78947368, 500.        ])

In [79]:
np.arange(3, 30, 10)

array([ 3, 13, 23])

In [80]:
np.exp(np.ones((5,5)))

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183]])

In [81]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [82]:
np.arange(100).reshape(25,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [83]:
data = u"\n".join(str(i) for i in range(10))

In [84]:
import numpy as np


In [85]:
a = np.arange(0,6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [86]:
b = np.transpose(a)

In [87]:
b

array([[0, 2, 4],
       [1, 3, 5]])

In [88]:
n = np.array([1, 2, 3, 4])

In [89]:
p = np.expand_dims(n, axis = 0)

In [90]:
q = np.expand_dims(n, axis = 1)

In [91]:
p

array([[1, 2, 3, 4]])

In [92]:
import numpy as np

In [93]:
a = np.array([[[1, 2, 3, 4]]])

In [94]:
b = np.squeeze(a, axis = 0)

In [95]:
import numpy as np
c = np.squeeze(b)


In [96]:
c

array([1, 2, 3, 4])

In [97]:
np.eye(3, 3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [98]:
b = np.arange(25).reshape(5,5)

In [99]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
b[0:2, :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
b[:, :]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [102]:
b[:, :4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [103]:
a = np.array([[[1,2],[3,4],[5,6]],# first axis array
[[7,8],[9,10],[11,12]],# second axis array
[[13,14],[15,16],[17,18]]])# third axis array

In [104]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [105]:
a[0:2, 0:3, 0:1]

array([[[ 1],
        [ 3],
        [ 5]],

       [[ 7],
        [ 9],
        [11]]])

In [106]:
a = np.array([[1,2,3],[4,5,6]])

In [107]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
np.append(a, [[5,6,7]], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [109]:
b = np.array([[2], [2]])

In [110]:
b

array([[2],
       [2]])

In [111]:
a*b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [112]:
a = np.arange(1,6)

In [113]:
b = np.arange(1,6)

In [117]:
a

array([1, 2, 3, 4, 5])

In [114]:
n = np.array([[1,2,3],[1,2,3]])

In [115]:
np.argmax(n)

2

In [116]:
help(np.argmax)

Help on function argmax in module numpy:

argmax(a, axis=None, out=None)
    Returns the indices of the maximum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed.
    
    See Also
    --------
    ndarray.argmax, argmin
    amax : The maximum value along a given axis.
    unravel_index : Convert a flat index into an index tuple.
    take_along_axis : Apply ``np.expand_dims(index_array, axis)`` 
                      from argmax to an array as if by calling max.
    
    Notes
    ---

In [120]:
a = np.array([[1, 2, 3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
print(a)

[[1 2 3]
 [4 5 6]]


In [124]:
column = []
for i in a:
    column.append(i[2])
    print(column)

[3]
[3, 6]


In [128]:
#array creation
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3.0], [4,5,6]])
c = np.array([[1,2,3], [5,5,6]], dtype = complex)

In [129]:
a,b,c

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[1.+0.j, 2.+0.j, 3.+0.j],
        [5.+0.j, 5.+0.j, 6.+0.j]]))