In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


In [5]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])

print(a)

a = a.reshape(2,3)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [21]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])
b = np.array([[1,2,3], [4,5,6]])

print(a.b)



AttributeError: 'numpy.ndarray' object has no attribute 'b'

In [6]:
import numpy as np
a = np.array([1, 2, 3, 4], dtype = complex)
print(a)
a.itemsize
type(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


numpy.ndarray

In [ ]:
a = np.array

In [1]:
pip instal pandas

ERROR: unknown command "instal" - maybe you meant "install"
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [5]:
help(list)


Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [6]:
help(numpy)

NameError: name 'numpy' is not defined

In [3]:
import numpy as np
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
cp = np.ones((2,3))

In [7]:
np.empty((5,5))

array([[4.68264634e-310, 0.00000000e+000, 6.92529544e-310,
        6.92529228e-310, 6.92529224e-310],
       [6.92529226e-310, 6.92529542e-310, 6.92529225e-310,
        6.92529227e-310, 6.92529543e-310],
       [6.92529226e-310, 6.92529224e-310, 6.92529225e-310,
        6.92529226e-310, 6.92529539e-310],
       [6.92529543e-310, 6.92529540e-310, 6.92529544e-310,
        6.92529544e-310, 6.92529538e-310],
       [6.92529481e-310, 6.92529481e-310, 6.92529544e-310,
        6.92529481e-310, 1.02765654e-321]])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(2, 500, 20)

array([  2.        ,  28.21052632,  54.42105263,  80.63157895,
       106.84210526, 133.05263158, 159.26315789, 185.47368421,
       211.68421053, 237.89473684, 264.10526316, 290.31578947,
       316.52631579, 342.73684211, 368.94736842, 395.15789474,
       421.36842105, 447.57894737, 473.78947368, 500.        ])

In [10]:
np.array.range(200)

AttributeError: 'builtin_function_or_method' object has no attribute 'range'

In [11]:
np.arange(3, 30, 10)

array([ 3, 13, 23])

In [13]:
np.exp(np.ones((5,5)))

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183]])

In [20]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [23]:
np.arange(100).reshape(25,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [25]:
data = u"\n".join(str(i) for i in range(10))

In [29]:
import numpy as np


In [33]:
a = np.arange(0,6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
b = np.transpose(a)

In [39]:
b

array([[0, 2, 4],
       [1, 3, 5]])

In [40]:
n = np.array([1, 2, 3, 4])

In [41]:
p = np.expand_dims(n, axis = 0)

In [45]:
q = np.expand_dims(n, axis = 1)

In [46]:
p

array([[1, 2, 3, 4]])

In [48]:
import numpy as np

In [4]:
a = np.array([[[1, 2, 3, 4]]])

In [5]:
b = np.squeeze(a, axis = 0)

In [6]:
import numpy as np
c = np.squeeze(b)


In [7]:
c

array([1, 2, 3, 4])

In [10]:
np.eye(3, 3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
b = np.arange(25).reshape(5,5)

In [15]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
b[0:2, :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
b[:, :]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
b[:, :4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [20]:
a = np.array([[[1,2],[3,4],[5,6]],# first axis array
[[7,8],[9,10],[11,12]],# second axis array
[[13,14],[15,16],[17,18]]])# third axis array

In [21]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [23]:
a[0:2, 0:3, 0:1]

array([[[ 1],
        [ 3],
        [ 5]],

       [[ 7],
        [ 9],
        [11]]])

In [26]:
a = np.array([[1,2,3],[4,5,6]])

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.append(a, [[5,6,7]], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [32]:
b = np.array([[2], [2]])

In [33]:
b

array([[2],
       [2]])

In [35]:
a*b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [36]:
a = np.arange(1,6)

In [37]:
b = np.arange(1,6)

610 ns ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [41]:
n = np.array([[1,2,3],[1,2,3]])

In [42]:
np.argmax(n)

2

In [43]:
help(np.argmax)

Help on function argmax in module numpy:

argmax(a, axis=None, out=None)
    Returns the indices of the maximum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed.
    
    See Also
    --------
    ndarray.argmax, argmin
    amax : The maximum value along a given axis.
    unravel_index : Convert a flat index into an index tuple.
    take_along_axis : Apply ``np.expand_dims(index_array, axis)``
                      from argmax to an array as if by calling max.
    
    Notes
    ----